# Travis CI configuration file.

language: php

# Declare versions of PHP to use. Use one decimal max.
php:
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"
    - "5.3"   
    - "5.2"

sudo: false

# Run test script commands.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
    # Search theme for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;
    


# upload releases back to github
before_deploy: 
  - echo "deploying to GitHub releases"

deploy:
  provider: releases
  user: pranali@promactinfo.com
  password: Promact2016
  api_key: "7ffa414e78717cefa57f1233a79d9afb2fd887a5"
  file: '*'  
  skip_cleanup: true
  on:    
    tags: true
