# Travis CI configuration file.

language: php

# Declare versions of PHP to use. Use one decimal max.
php:
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"
    - "5.3"   
    - "5.2"

sudo: false

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
    # Search theme for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;
    


# upload releases back to github
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  user: "pranali2016"
  password: "Promact2016"
  file_glob: true
  file: "${RELEASE_PKG_FILE}"

  skip_cleanup: true
  on:
    tags: true	